Финальный проект спринта № 11
fen1x63/java-filmorate pull request #12
Opened 2023-08-07 12:12 UTC by fen1x63

2023-08-07 17:12 UTC, NikolaiDem requested changes

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        throw new EntityNotFoundException("Фильм не найден.");
Если rows <= 0, то
 mpaDbStorage.addMpaToFilm(film);
        genreDbStorage.updateGenresForCurrentFilm(film);
        genreDbStorage.addGenreNameToFilm(film);
        film.setGenres(genreDbStorage.getGenreForCurrentFilm(film.getId()));
        выполняться не должны

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (RuntimeException e) {
Перехватывать RuntimeException - плохая практика. Выглядит как "что бы там ни случилось, верните одну ошибку"

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    public Set<Genre> getGenreForCurrentFilm(int id) {
Этот метод больше подходит для FilmDbStorage

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +            if (genreRows.getLong("film_id") == id) {
Фильтр по film_id лучше сделать в запросе

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        film.getGenres().forEach(g -> {
Для множественного обновления лучше использовать jdbcTemplate.batchUpdate(String sql, final BatchPreparedStatementSetter pss), чтобы сделать это одним запросом.

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        } catch (RuntimeException e) {
Перехватывать RuntimeException плохая практика

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        } catch (RuntimeException e) {
Перехватывать RuntimeException плохая практика

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        } catch (RuntimeException e) {
Перехватывать RuntimeException плохая практика

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                "(SELECT friend_id FROM friends WHERE user_id=?)";
Заменить вложенный запрос джойном

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                "AND user_id IN(SELECT friend_id FROM friends WHERE user_id = ?)";
Заменить вложенный запрос джойном

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    private void validationUser(User user) throws ValidationException {
Это все же не валидация, а бизнес логика. Перенести в сервис

2023-08-07 17:12 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Удалять все таблицы не нужно

2023-08-20 19:04 UTC, NikolaiDem requested changes

2023-08-20 19:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        findAll().forEach(mpa -> {
Зачем искать все mpa?

2023-08-20 19:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        } catch (RuntimeException e) {
Перехватывать RuntimeException - плохая практика

2023-08-20 19:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/validator/ReleaseDateConstraintValidator.java
> +    public void initialize(ReleaseDate releaseDate) {
Не нужно переопределять

2023-08-26 23:40 UTC, fen1x63 commented
api-tests.yml и checkstyle не пускает как бинарные файлы

2023-08-27 18:59 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        } catch (RuntimeException e) {
Лучше уточнить тип перехватываемого исключения, например, DataAccessException

2023-08-27 19:17 UTC, NikolaiDem requested changes
Михаил, здесь должны быть выполнены 2 проверки. Предполагаю, они не работают из-за модификации файлов родительского репозитория
![image](https://github.com/fen1x63/java-filmorate/assets/37100322/c8c14185-0654-48b5-ac02-df5ed44e930e)

2023-08-27 19:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (getUserById(userId) == null) {
Проверку существования пользователя лучше вынести в сервис

2023-08-27 19:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            Set genres,
Raw use of parameterized class 'Set' 
Set лучше использовать с дженериком Set<Genre>

2023-08-27 19:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private static Film filmBl(
Метод больше относится к классу Film

2023-08-27 19:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Все служебные методы должны быть private

2023-08-27 19:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<User> getFriendsByUserId(Integer id) {
Этот метод здесь не нужен

2023-08-27 19:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private User mapRowToUser(ResultSet resultSet, int rowNum) throws SQLException {
Этот метод здесь не нужен

2023-08-27 19:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Mpa mpa = getMpaById(rs.getInt("rating_mpa_id"));
В rs ( в селект) еще лучше добавить name (из mpa_type), чтобы сразу сконструировать mpa без дополнительного запроса

2023-08-27 19:17 UTC, NikolaiDem commented on checkstyle.xml
> -<?xml version="1.0" encoding="UTF-8"?>
Не исправлено

2023-08-27 19:17 UTC, NikolaiDem commented on api-tests.yml
> -name: Films API Tests
Не исправлено

2023-08-28 14:25 UTC, fen1x63 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Mpa mpa = getMpaById(rs.getInt("rating_mpa_id"));
Mpa mpa = new Mpa(rs.getInt("rating_mpa_id"),rs.getString("mpa_name")); почему без доп. запроса не может найти фильм в дальнейшем?

2023-08-28 17:43 UTC, closed without merging