Спринт 11
fen1x63/java-filmorate pull request #15
Opened 2023-08-28 17:49 UTC by fen1x63

2023-08-28 19:27 UTC, fen1x63 commented
Чтобы заработал check , пришлось заново создать ветку

2023-08-29 19:16 UTC, NikolaiDem requested changes

2023-08-29 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> findAllFilms() {
Проблема N+1 запроса решается таким образом, например, (добавить отсутствующие методы)
    public List<Film> findAllFilms() {
        String sqlQuery = "SELECT films.*, mpa_type.mpa_name FROM films JOIN mpa_type ON films.rating_mpa_id =" +
            " mpa_type.rating_mpa_id";
        List<Film> films = jdbcTemplate.query(sqlQuery, this::makeFilm);
        Map<Integer, Film> filmById = films.stream()
            .collect(Collectors.toMap(Film::getId, Function.identity()));
        jdbcTemplate.query(
            "SELECT * " +
                "FROM genre " +
                "WHERE film_id in  " + //здесь записать все id фильмов
                "ORDER BY genre_id ASC",
            resultSet -> {
                Genre genre = Genre.builder()
                    .id(resultSet.getInt("genre_id"))
                    .name(resultSet.getString("name"))
                    .build();
                Film film = filmById.get(resultSet.getInt("film_id"));
                film.addGenre(genre);
            });

        return films;
    }

Аналогично для лайков.
Аналогично для getPopularFilms

2023-08-29 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    public void updateGenresForCurrentFilm(Film film) {
Не используется

2023-08-29 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +public class LikeDbStorage implements LikeStorage {
Классы, использующиеся только в тестах, должны быть в директории test

2023-08-29 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        } catch (RuntimeException e) {
Перехватывать Runtime исключения нехорошо

2023-08-29 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public UserDbStorage(JdbcTemplate jdbcTemplate, @Lazy UserService userService) {
Для чего здесь Lazy?

2023-08-31 12:25 UTC, closed without merging